services:
  # =======================
  # Controllers (3 nodes)
  # =======================
  controller1:
    image: confluentinc/cp-kafka:7.5.0
    hostname: controller1
    container_name: controller1
    environment:
      KAFKA_PROCESS_ROLES: controller
      KAFKA_NODE_ID: 1
      CLUSTER_ID: 2liwSXdgQRq8vuE_hY7oJA

      KAFKA_LISTENERS: CONTROLLER://0.0.0.0:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_CONTROLLER_QUORUM_VOTERS: |
        1@controller1:9093,2@controller2:9093,3@controller3:9093

      KAFKA_LOG_DIRS: /var/lib/kafka/data

    volumes:
      - controller1_data:/var/lib/kafka/data
    networks:
          - datalake

  controller2:
    image: confluentinc/cp-kafka:7.5.0
    hostname: controller2
    container_name: controller2
    environment:
      KAFKA_PROCESS_ROLES: controller
      KAFKA_NODE_ID: 2
      CLUSTER_ID: 2liwSXdgQRq8vuE_hY7oJA

      KAFKA_LISTENERS: CONTROLLER://0.0.0.0:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_CONTROLLER_QUORUM_VOTERS: |
        1@controller1:9093,2@controller2:9093,3@controller3:9093

      KAFKA_LOG_DIRS: /var/lib/kafka/data

    volumes:
      - controller2_data:/var/lib/kafka/data
    networks:
          - datalake

  controller3:
    image: confluentinc/cp-kafka:7.5.0
    hostname: controller3
    container_name: controller3
    environment:
      KAFKA_PROCESS_ROLES: controller
      KAFKA_NODE_ID: 3
      CLUSTER_ID: 2liwSXdgQRq8vuE_hY7oJA

      KAFKA_LISTENERS: CONTROLLER://0.0.0.0:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_CONTROLLER_QUORUM_VOTERS: |
        1@controller1:9093,2@controller2:9093,3@controller3:9093

      KAFKA_LOG_DIRS: /var/lib/kafka/data

    volumes:
      - controller3_data:/var/lib/kafka/data
    networks:
          - datalake

  # =======================
  # Brokers (3 nodes)
  # =======================
  broker1:
    image: confluentinc/cp-kafka:7.5.0
    hostname: broker1
    container_name: broker1
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: broker
      KAFKA_NODE_ID: 4
      CLUSTER_ID: 2liwSXdgQRq8vuE_hY7oJA

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_CONTROLLER_QUORUM_VOTERS: |
        1@controller1:9093,2@controller2:9093,3@controller3:9093

      KAFKA_LOG_DIRS: /var/lib/kafka/data

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 2

    volumes:
      - broker1_data:/var/lib/kafka/data
    networks:
          - datalake

  broker2:
    image: confluentinc/cp-kafka:7.5.0
    hostname: broker2
    container_name: broker2
    environment:
      KAFKA_PROCESS_ROLES: broker
      KAFKA_NODE_ID: 5
      CLUSTER_ID: 2liwSXdgQRq8vuE_hY7oJA

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker2:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_CONTROLLER_QUORUM_VOTERS: |
        1@controller1:9093,2@controller2:9093,3@controller3:9093

      KAFKA_LOG_DIRS: /var/lib/kafka/data

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 2

    volumes:
      - broker2_data:/var/lib/kafka/data
    networks:
          - datalake

  broker3:
    image: confluentinc/cp-kafka:7.5.0
    hostname: broker3
    container_name: broker3
    environment:
      KAFKA_PROCESS_ROLES: broker
      KAFKA_NODE_ID: 6
      CLUSTER_ID: 2liwSXdgQRq8vuE_hY7oJA

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker3:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_CONTROLLER_QUORUM_VOTERS: |
        1@controller1:9093,2@controller2:9093,3@controller3:9093

      KAFKA_LOG_DIRS: /var/lib/kafka/data

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 2

    volumes:
      - broker3_data:/var/lib/kafka/data
    networks:
      - datalake

volumes:
  controller1_data:
  controller2_data:
  controller3_data:
  broker1_data:
  broker2_data:
  broker3_data:

networks:
  datalake:
    external: true